name: Lint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
      - uses: actions/checkout@v3
      - uses: marian-code/python-lint-annotate@v3
        with:
          python-root-list: "bindpy/ tests/ examples/"
          use-flake8: true
          use-black: true
          python-version: ${{ matrix.python-version }}
